# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1048bb00097e77e4c8ad325b522f0cdfd934bd83a9aca3dff28a4259a58ff577b452221eb45ce1ca52889232c4f111ff63f6211e0c94eee5925aeca195221709

test:
  secret_key_base: 1d6ea2d01ce7a3a10ddd4b42532a6cfd46e504382c6b847643f0d7167cbbeff5d5834b75c5ae2de56ce9ad49003370b9f068655c58daa867149bed624ae08d5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
